"""empty message

Revision ID: 276827933149
Revises: 0763d677d453
Create Date: 2026-03-08 20:14:30.571308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '276827933149'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.Enum('SPORTS', 'MUSIC', 'ART', 'FOOD', 'TRAVEL', name='categoryactivity'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=250), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('nickname', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='statususer'), nullable=False))
        batch_op.add_column(sa.Column('role', sa.Enum('ADMIN', 'USER', name='roleuser'), nullable=False))
        batch_op.drop_constraint(batch_op.f('user_email_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['nickname'])
        batch_op.drop_column('is_active')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('user_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('role')
        batch_op.drop_column('status')
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('nickname')
        batch_op.drop_column('name')

    op.drop_table('favorite')
    op.drop_table('activity')
    # ### end Alembic commands ###
