"""add fc to user

Revision ID: 5ff2c2fbd4cf
Revises: 8e1b2a22aa42
Create Date: 2026-04-05 19:50:53.653932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff2c2fbd4cf'
down_revision = '8e1b2a22aa42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('fc', sa.String(length=120), nullable=True))

    op.execute('UPDATE "user" SET fc = nickname WHERE fc IS NULL')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column(
            'fc', existing_type=sa.String(length=120), nullable=False)
        batch_op.create_unique_constraint('uq_user_fc', ['fc'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_fc', type_='unique')
        batch_op.drop_column('fc')

    # ### end Alembic commands ###
