"""empty message

Revision ID: 8e1b2a22aa42
Revises: 386d4f5b0211
Create Date: 2026-03-28 21:09:48.379805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e1b2a22aa42'
down_revision = '386d4f5b0211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=250), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###
