"""empty message

Revision ID: 96129a1b03de
Revises: 276827933149
Create Date: 2026-03-28 20:23:02.523316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96129a1b03de'
down_revision = '276827933149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=250), nullable=True))
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
