"""add code to user

Revision ID: b9553a6206ef
Revises: 5ff2c2fbd4cf
Create Date: 2026-04-05 20:01:28.443943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9553a6206ef'
down_revision = '5ff2c2fbd4cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('code', sa.String(length=120), nullable=True))

    op.execute('UPDATE "user" SET code = nickname WHERE code IS NULL')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column(
            'code', existing_type=sa.String(length=120), nullable=False)
        batch_op.create_unique_constraint('uq_user_code', ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_code', type_='unique')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
